name: Trigger Infineon/infineon-design-system-stencil update

# on:
#   workflow_run:
#     workflows: ["Deploy Library to GitHub"]
#     types:
#       - completed

on: #just for testing
  pull_request:
    types:
      - opened
      - reopened
      - synchronize # canary on new commit

  workflow_dispatch:

jobs:
  send_repo_dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          script: |
            try {
              const result = await github.rest.repos.createDispatchEvent({
                owner: 'Infineon',
                repo: 'Infineon-Design-System-Stencil',
                event_type: 'infineon_icons_release',
                client_payload: {"version": "v5.3.10"}
              });
              console.log(result);
            } catch (error) {
              console.error(error);
            }
          